mutation ($id: UUID) {
  result: summaryInsert(
    summary: {id: $id}
  ) {
    __typename
    ...Error
    ...Summary
  }
}

fragment Error on SummaryGQLModelInsertError {
	__typename
}

fragment Summary on SummaryGQLModel {
    id
    lastchange
    effectiveDate
    expirationDate
    pointRange
}