query ($id: UUID!) {
  result: summaryById(id: $id) {
    __typename
    ...Summary
  }
}

fragment Summary on SummaryGQLModel {
    id
    lastchange
    effectiveDate
    expirationDate
    pointRange
    createdby { id }
    changedby { id }
    rbacobject { id }
}