mutation ($id: UUID!, $lastchange: DateTime!, $effective_date: DateTime) {
  result: summaryUpdate(
    summary: {id: $id, lastchange: $lastchange, effectiveDate: $effective_date}
  ) {
    __typename
    ...Summary
    ...Error
  }
}

fragment Error on SummaryGQLModelUpdateError {
	failed
}

fragment Summary on SummaryGQLModel {
    id
    lastchange
    effectiveDate
    expirationDate
    pointRange
}