mutation ($id: UUID, $summary_id: UUID, $name: String!) {
  result: disciplineInsert(
    discipline: {id: $id, name: $name, summaryId: $summary_id}
  ) {
    __typename
    ...Error
    ...Discipline
  }
}

fragment Error on DisciplineGQLModelInsertError {
	__typename
}

fragment Discipline on DisciplineGQLModel {
    id
    lastchange
    name
    nameEn
    description
}