mutation ($id: UUID!, $lastchange: DateTime!, $name: String!) {
  result: disciplineUpdate(
    discipline: {id: $id, lastchange: $lastchange, name: $name}
  ) {
    __typename
    ...Discipline
    ...Error
  }
}

fragment Error on DisciplineGQLModelUpdateError {
	failed
}

fragment Discipline on DisciplineGQLModel {
    id
    lastchange
    name
    nameEn
    description
}