mutation ($id: UUID!, $lastchange: DateTime!, $summary_id: UUID, $name: String!) {
  result: disciplineUpdate(
    discipline: {id: $id, lastchange: $lastchange, name: $name, summaryId: $summary_id}
  ) {
    __typename
    ...Discipline
    ...Error
  }
}

fragment Error on DisciplineGQLModelUpdateError {
	failed
}

fragment Discipline on DisciplineGQLModel {
    id
    lastchange
    name
    nameEn
    description
    summary { id }
}