mutation ($id: UUID, $summary_id: UUID, $name: String!, $valid: Boolean) {
  result: disciplineUpdate(
    discipline: {id: $id, name: $name, summaryId: $summary_id, valid: $valid}
  ) {
    __typename
    ...Error
    ...Discipline
  }
}

fragment Error on DisciplineGQLModelUpdateError {
	__typename
}

fragment Discipline on DisciplineGQLModel {
    id
    lastchange
    name
    name_en
    description
    summary { id }
}