mutation ($id: UUID) {
  result: normInsert(
    norm: {id: $id}
  ) {
    __typename
    ...Error
    ...Norm
  }
}

fragment Error on NormGQLModelInsertError {
	__typename
}

fragment Norm on NormGQLModel {
    id
    lastchange
    effectiveDate
    expirationDate
    male
    female
    ageMinimal
    ageMaximal
    resultMinimalValue
    resultMaximalValue
    points
}