query ($id: UUID!) {
  result: normById(id: $id) {
    __typename
    ...Norm
  }
}

fragment Norm on NormGQLModel {
    id
    lastchange
    effectiveDate
    expirationDate
    male
    female
    ageMinimal
    ageMaximal
    resultMinimalValue
    resultMaximalValue
    points
    createdby { id }
    changedby { id }
    rbacobject { id }
}