mutation ($id: UUID, $name: String!, $valid: Boolean) {
  result: normUpdate(
    norm: {id: $id, name: $name, valid: $valid}
  ) {
    __typename
    ...Error
    ...Norm
  }
}

fragment Error on NormGQLModelUpdateError {
	failed
}

fragment Norm on NormGQLModel {
    id
    lastchange
    effective_date
    expiration_date
    male
    female
    age_minimal
    age_maximal
    result_minimal_value
    result_maximal_value
    points
}