mutation ($id: UUID!, $lastchange: DateTime!, $effective_date: DateTime) {
  result: normUpdate(
    norm: {id: $id, lastchange: $lastchange, effectiveDate: $effective_date}
  ) {
    __typename
    ...Norm
    ...Error
  }
}

fragment Error on NormGQLModelUpdateError {
	failed
}

fragment Norm on NormGQLModel {
    id
    lastchange
    effectiveDate
    expirationDate
    male
    female
    ageMinimal
    ageMaximal
    resultMinimalValue
    resultMaximalValue
    points
}