mutation ($id: UUID, $summary_id: UUID, $name: String!) {
  result: disciplineSetInsert(
    disciplineSet: {id: $id, name: $name, summaryId: $summary_id}
  ) {
    __typename
    ...Error
    ...DisciplineSet
  }
}

fragment Error on DisciplineSetGQLModelInsertError {
	__typename
}

fragment DisciplineSet on DisciplineSetGQLModel {
    id
    lastchange
    name
    nameEn
    description
    minimumPoints
}