query ($id: UUID!) {
  result: disciplineSetById(id: $id) {
    __typename
    ...DisciplineSet
  }
}

fragment DisciplineSet on DisciplineSetGQLModel {
    id
    lastchange
    name
    nameEn
    description
    minimumPoints
    summary { id }
    createdby { id }
    changedby { id }
    rbacobject { id }
}