mutation ($id: UUID!, $lastchange: DateTime!, $summary_id: UUID, $name: String!) {
  result: disciplineSetUpdate(
    disciplineSet: {id: $id, lastchange: $lastchange, name: $name, summaryId: $summary_id}
  ) {
    __typename
    ...DisciplineSet
    ...Error
  }
}

fragment Error on DisciplineSetGQLModelUpdateError {
	failed
}

fragment DisciplineSet on DisciplineSetGQLModel {
    id
    lastchange
    name
    nameEn
    description
    minimumPoints
    summary { id }
}